### ISSUE TITLE
Boost Review: Post feedback here or elsewhere?

### ISSUE THREAD

**Issue by daixtrose** [joaquintides/poly_collection#4]
It is rather convenient to post tiny questions and review items here, but at the same time there are the boot mailing lists and [the boost incubator](http://blincubator.com/). 

@joaquintides Where do you want feedback to go?

**Comment by joaquintides** [comment]
Hi Markus,

I'd rather you posted your feedback on the mailing list, as there's a review going on and other potential reviewers can benefit from your opinions. Thank you!

**Comment by daixtrose** [comment]
OK, thanks for the feedback
